language: node_js
node_js:
- node
git:
  depth: 1
cache:
  directories:
  - node_modules/
install:
- npm install
before_script:
- npm run build
script:
- npm test
after_success:
- npm install -g firebase-tools
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then firebase deploy --project production --token
  "$FIREBASE_TOKEN" --message "$TRAVIS_COMMIT_MESSAGE"; fi